version: '3'

services:
  alert-bot:
    image: alert_bot_dev:latest
    container_name: alert_bot_dev
    build: .
    env_file:
      - ./environments/dev.env
    volumes:
      - ~/docker/data/alert_bot:/data
    restart: unless-stopped
